FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=prod

ARG ORIGINAL_JAR_FILE=./build/libs/search-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} search-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/search-service.jar"]
